
services:
  db:
    image: postgres:15-alpine 
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: postgres   
      POSTGRES_PASSWORD: secret 
      POSTGRES_DB: auth_service_db       
    ports:
      - "5432:5432"             
    volumes:
      - postgres_data:/var/lib/postgresql/data  

volumes:
  postgres_data:  